// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6C_SucYJPXIH0WA8xRRdWiU_3jkDKoRU',
    appId: '1:675199172152:android:4a2aef9021228db808f0cd',
    messagingSenderId: '675199172152',
    projectId: 'bloc-photo-library-course',
    storageBucket: 'bloc-photo-library-course.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDavN7NYvJq7FQdPBfWX10nC326CbUOR8Q',
    appId: '1:675199172152:ios:506e997dbfe3450c08f0cd',
    messagingSenderId: '675199172152',
    projectId: 'bloc-photo-library-course',
    storageBucket: 'bloc-photo-library-course.appspot.com',
    iosClientId: '675199172152-maccc64h2ihuj96m6o4uo6qbfi2rl2gm.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.bloc-photo-library-course',
  );
}
